"""added initial user game event tables

Revision ID: 406221675ff8
Revises: 
Create Date: 2019-09-19 18:47:16.802198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406221675ff8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.Column('appid', sa.BigInteger(), nullable=True),
    sa.Column('gamename', sa.Text(), nullable=True),
    sa.Column('about_the_game', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('content_descriptors', sa.Text(), nullable=True),
    sa.Column('controller_support', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('developers', sa.Text(), nullable=True),
    sa.Column('dlc', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('header_image', sa.Text(), nullable=True),
    sa.Column('is_free', sa.Text(), nullable=True),
    sa.Column('legal_notice', sa.Text(), nullable=True),
    sa.Column('linux_requirements', sa.Text(), nullable=True),
    sa.Column('mac_requirements', sa.Text(), nullable=True),
    sa.Column('metacritic', sa.Text(), nullable=True),
    sa.Column('movies', sa.Text(), nullable=True),
    sa.Column('package_groups', sa.Text(), nullable=True),
    sa.Column('pc_requirements', sa.Text(), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('publishers', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Text(), nullable=True),
    sa.Column('required_age', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('support_info', sa.Text(), nullable=True),
    sa.Column('supported_languages', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('gameid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('communityvisibilitystate', sa.Integer(), nullable=True),
    sa.Column('profilestate', sa.Integer(), nullable=True),
    sa.Column('personaname', sa.Text(), nullable=True),
    sa.Column('lastlogoff', sa.Integer(), nullable=True),
    sa.Column('profileurl', sa.Text(), nullable=True),
    sa.Column('avatarfull', sa.Text(), nullable=True),
    sa.Column('personastate', sa.Integer(), nullable=True),
    sa.Column('primaryclanid', sa.BigInteger(), nullable=True),
    sa.Column('timecreated', sa.BigInteger(), nullable=True),
    sa.Column('personastateflags', sa.Integer(), nullable=True),
    sa.Column('loccountrycode', sa.String(), nullable=True),
    sa.Column('locstatecode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('gameevents',
    sa.Column('gameeventsid', sa.Integer(), nullable=False),
    sa.Column('gameeventname', sa.Text(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('gameeventdate', sa.DateTime(), nullable=True),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['game.gameid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('gameeventsid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameevents')
    op.drop_table('user')
    op.drop_table('game')
    # ### end Alembic commands ###
